# Generated by Django 3.0.3 on 2020-02-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacttb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(blank=True, max_length=30, null=True)),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('sub', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
